### ISSUE TITLE
Can't find assembly references directory in Linux

### ISSUE THREAD

**Issue by ghost** [Philip-Trettner/GlmSharp#11]
If I downloaded GlmSharp via command-line in Ubuntu with `nuget install glmsharp` then where would the assembly references be located...?
I have tried `mcs -pkg:glm test.cs`, `mcs -pkg:glmsharp test.cs`, etc... and have had no luck in locating them in the filesystem.

Would you have any suggestions?

Thanks

**Comment by Philip-Trettner** [comment]
Hm I've never used it on linux before.

GlmSharp has the following assembly refs:
```
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
```
I'm not sure if all of them are supported on linux.

There is also GlmSharpCompat, which has less references and only uses:
```
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
```
so you could test if that works.

**Comment by jackw1111** [comment]
Thanks for the prompt reply.

Okay, no problem. I am new to C#, but from what I gather, on Linux anyway, packages are in the file format `example-package.pc`, and you can find where the path to these files with `pkg-config --variable pc_path pkg-config`. So for something like GtkSharp, as long as it is in the path, you can link to it when compiling `mcs -pkg:gtk-sharp-2.0 helloworld.cs` and use it in the program. But I can't seem to find where nuget would store the `glmsharp.pc`.

**Comment by ghost** [comment]
Wow okay. I discovered that it was installed in current directory. 

All I had to do was `mcs -reference:/path/to/GlmSharp.0.9.8/lib/Net20/GlmSharp.dll example.cs`.

My bad. XD.

Thanks anyway.
